"""empty message

Revision ID: 4498a3847c90
Revises: d5913f8d6133
Create Date: 2025-12-19 21:30:58.737076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4498a3847c90'
down_revision: Union[str, Sequence[str], None] = 'd5913f8d6133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gold_open', sa.Float(), nullable=True),
    sa.Column('gold_high', sa.Float(), nullable=True),
    sa.Column('gold_low', sa.Float(), nullable=True),
    sa.Column('gold_close', sa.Float(), nullable=True),
    sa.Column('gold_adj_close', sa.Float(), nullable=True),
    sa.Column('gold_volume', sa.BigInteger(), nullable=True),
    sa.Column('sp_open', sa.Float(), nullable=True),
    sa.Column('sp_high', sa.Float(), nullable=True),
    sa.Column('sp_low', sa.Float(), nullable=True),
    sa.Column('sp_close', sa.Float(), nullable=True),
    sa.Column('sp_adj_close', sa.Float(), nullable=True),
    sa.Column('sp_volume', sa.BigInteger(), nullable=True),
    sa.Column('dj_open', sa.Float(), nullable=True),
    sa.Column('dj_high', sa.Float(), nullable=True),
    sa.Column('dj_low', sa.Float(), nullable=True),
    sa.Column('dj_close', sa.Float(), nullable=True),
    sa.Column('dj_adj_close', sa.Float(), nullable=True),
    sa.Column('dj_volume', sa.BigInteger(), nullable=True),
    sa.Column('eg_open', sa.Float(), nullable=True),
    sa.Column('eg_high', sa.Float(), nullable=True),
    sa.Column('eg_low', sa.Float(), nullable=True),
    sa.Column('eg_close', sa.Float(), nullable=True),
    sa.Column('eg_adj_close', sa.Float(), nullable=True),
    sa.Column('eg_volume', sa.BigInteger(), nullable=True),
    sa.Column('eu_price', sa.Float(), nullable=True),
    sa.Column('eu_open', sa.Float(), nullable=True),
    sa.Column('eu_high', sa.Float(), nullable=True),
    sa.Column('eu_low', sa.Float(), nullable=True),
    sa.Column('eu_trend', sa.Integer(), nullable=True),
    sa.Column('of_price', sa.Float(), nullable=True),
    sa.Column('of_open', sa.Float(), nullable=True),
    sa.Column('of_high', sa.Float(), nullable=True),
    sa.Column('of_low', sa.Float(), nullable=True),
    sa.Column('of_volume', sa.BigInteger(), nullable=True),
    sa.Column('of_trend', sa.Integer(), nullable=True),
    sa.Column('os_price', sa.Float(), nullable=True),
    sa.Column('os_open', sa.Float(), nullable=True),
    sa.Column('os_high', sa.Float(), nullable=True),
    sa.Column('os_low', sa.Float(), nullable=True),
    sa.Column('os_trend', sa.Integer(), nullable=True),
    sa.Column('sf_price', sa.Float(), nullable=True),
    sa.Column('sf_open', sa.Float(), nullable=True),
    sa.Column('sf_high', sa.Float(), nullable=True),
    sa.Column('sf_low', sa.Float(), nullable=True),
    sa.Column('sf_volume', sa.BigInteger(), nullable=True),
    sa.Column('sf_trend', sa.Integer(), nullable=True),
    sa.Column('usb_price', sa.Float(), nullable=True),
    sa.Column('usb_open', sa.Float(), nullable=True),
    sa.Column('usb_high', sa.Float(), nullable=True),
    sa.Column('usb_low', sa.Float(), nullable=True),
    sa.Column('usb_trend', sa.Integer(), nullable=True),
    sa.Column('plt_price', sa.Float(), nullable=True),
    sa.Column('plt_open', sa.Float(), nullable=True),
    sa.Column('plt_high', sa.Float(), nullable=True),
    sa.Column('plt_low', sa.Float(), nullable=True),
    sa.Column('plt_trend', sa.Integer(), nullable=True),
    sa.Column('pld_price', sa.Float(), nullable=True),
    sa.Column('pld_open', sa.Float(), nullable=True),
    sa.Column('pld_high', sa.Float(), nullable=True),
    sa.Column('pld_low', sa.Float(), nullable=True),
    sa.Column('pld_trend', sa.Integer(), nullable=True),
    sa.Column('rho_price', sa.Float(), nullable=True),
    sa.Column('usdi_price', sa.Float(), nullable=True),
    sa.Column('usdi_open', sa.Float(), nullable=True),
    sa.Column('usdi_high', sa.Float(), nullable=True),
    sa.Column('usdi_low', sa.Float(), nullable=True),
    sa.Column('usdi_volume', sa.BigInteger(), nullable=True),
    sa.Column('usdi_trend', sa.Integer(), nullable=True),
    sa.Column('gdx_open', sa.Float(), nullable=True),
    sa.Column('gdx_high', sa.Float(), nullable=True),
    sa.Column('gdx_low', sa.Float(), nullable=True),
    sa.Column('gdx_close', sa.Float(), nullable=True),
    sa.Column('gdx_adj_close', sa.Float(), nullable=True),
    sa.Column('gdx_volume', sa.BigInteger(), nullable=True),
    sa.Column('uso_open', sa.Float(), nullable=True),
    sa.Column('uso_high', sa.Float(), nullable=True),
    sa.Column('uso_low', sa.Float(), nullable=True),
    sa.Column('uso_close', sa.Float(), nullable=True),
    sa.Column('uso_adj_close', sa.Float(), nullable=True),
    sa.Column('uso_volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketdata_date'), 'marketdata', ['date'], unique=True)
    op.create_index(op.f('ix_marketdata_id'), 'marketdata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketdata_id'), table_name='marketdata')
    op.drop_index(op.f('ix_marketdata_date'), table_name='marketdata')
    op.drop_table('marketdata')
    # ### end Alembic commands ###
