"""Add SKU description and vendor to material

Revision ID: 4a50f4668530
Revises: be0029af8533
Create Date: 2025-12-21 19:28:56.927823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a50f4668530'
down_revision: Union[str, Sequence[str], None] = 'be0029af8533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('material', sa.Column('description', sa.String(), nullable=True))
    op.add_column('material', sa.Column('preferred_vendor', sa.String(), nullable=True))
    op.create_index(op.f('ix_material_sku'), 'material', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_sku'), table_name='material')
    op.drop_column('material', 'preferred_vendor')
    op.drop_column('material', 'description')
    op.drop_column('material', 'sku')
    # ### end Alembic commands ###
