"""Update Market Data

Revision ID: 8f8df5f8ee57
Revises: 7f17241f4259
Create Date: 2026-03-02 19:59:51.719248

"""
# Migration to update the marketdata table with additional technical indicators.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8df5f8ee57'
down_revision: Union[str, Sequence[str], None] = '7f17241f4259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketdata', sa.Column('ma_7', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('ma_30', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('ma_90', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('daily_return', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('volatility_7', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('volatility_30', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('rsi', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('macd', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('macd_signal', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('bb_upper', sa.Float(), nullable=True))
    op.add_column('marketdata', sa.Column('bb_lower', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketdata', 'bb_lower')
    op.drop_column('marketdata', 'bb_upper')
    op.drop_column('marketdata', 'macd_signal')
    op.drop_column('marketdata', 'macd')
    op.drop_column('marketdata', 'rsi')
    op.drop_column('marketdata', 'volatility_30')
    op.drop_column('marketdata', 'volatility_7')
    op.drop_column('marketdata', 'daily_return')
    op.drop_column('marketdata', 'ma_90')
    op.drop_column('marketdata', 'ma_30')
    op.drop_column('marketdata', 'ma_7')
    # ### end Alembic commands ###
