"""Add transaction status and debt columns

Revision ID: b30026230124
Revises: 7f420f2716c8
Create Date: 2025-12-27 19:52:24.020108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30026230124'
down_revision: Union[str, Sequence[str], None] = '7f420f2716c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('status', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('balance_due', sa.Float(), nullable=True))
    op.create_index(op.f('ix_transaction_status'), 'transaction', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_status'), table_name='transaction')
    op.drop_column('transaction', 'balance_due')
    op.drop_column('transaction', 'amount_paid')
    op.drop_column('transaction', 'status')
    # ### end Alembic commands ###
