"""Create material inventory table

Revision ID: be0029af8533
Revises: 4498a3847c90
Create Date: 2025-12-19 21:57:07.181832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0029af8533'
down_revision: Union[str, Sequence[str], None] = '4498a3847c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_category'), 'material', ['category'], unique=False)
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.create_index(op.f('ix_material_name'), 'material', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_name'), table_name='material')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_index(op.f('ix_material_category'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
